import pickle

import xarray as xr
import argparse
import datetime

# update FASTMIP output file attributes

def update_attributes(ds, fair_members_attr):
    # global attributes:
    # remove old ones:
    for key in ['axis','standard_name','long_name','units']:
        ds.attrs.pop(key, None)

    # update new ones:
    ds.attrs.update({
        'meteor_version': 'tag v1.6.0-37-g4dcd6f3',
        'reference': 'https://doi.org/10.5194/egusphere-2026-2029 [preprint]',
        'ensemble_info': 'Full ensemble is 200 members per ESM per scenario (20 randomly chosen FAIR GSAT ensemble members x 10 METEOR noise/internal variability realisations). FAIR realisations are shared across ESMs and scenarios, noise realisations are independently generated by METEOR for each ensemble member.',
        'fair_calibration': 'Fair configuration v2.2.4, calibration 1.6.0-forced',
        '20 FAIR ensemble_members': fair_members_attr,
        'authors': 'Maura Dewey (maura.dewey@cicero.oslo.no), Marit Sandstad (marit.sandstad@cicero.oslo.no), Ben Sanderson (benjamin.sanderson@cicero.oslo.no)',
        'date': datetime.datetime.now(datetime.UTC).isoformat()
        })

    # variable specific attributes:
    if 'tas' in ds.variables:
        ds['tas'].attrs.update({
            'description': 'Temperature emulation for FASTMIP phase 2',
            'units': 'K',
            'long_name': 'Near-surface air temperature anomaly',
            'standard_name': 'air_temperature',
            'reference_period': 'piControl'
        })
    if 'tas_mean' in ds.variables:
        ds['tas_mean'].attrs.update({
            'description': 'Temperature emulation for FASTMIP phase 2',
            'units': 'K',
            'long_name': 'Near-surface air temperature anomaly',
            'standard_name': 'air_temperature',
            'reference_period': 'piControl'
        })

    if 'pr' in ds.variables:
        ds['pr'].attrs.update({
            'description': 'Precipitation emulation for FASTMIP phase 2',
            'units': 'kg m-2 s-1',
            'long_name': 'Near-surface precipitation rate anomaly',
            'standard_name': 'precipitation_flux',
            'reference_period': 'piControl'
        })
    if 'pr_mean' in ds.variables:
        ds['pr_mean'].attrs.update({
            'description': 'Precipitation emulation for FASTMIP phase 2',
            'units': 'kg m-2 s-1',
            'long_name': 'Near-surface precipitation rate anomaly',
            'standard_name': 'precipitation_flux',
            'reference_period': 'piControl'
        })

    if 'var_scenario' in ds.variables:
        ds.attrs.update({
            'description': 'variance decomposition from: ESMs, FAIR GSAT ensemble members (global response), CMIP7 scenarios, and METEOR internal variability.'
        })
    
    if 'var_global' in ds.variables and 'var_scenario' not in ds.variables:
        ds.attrs.update({
            'description': 'variance decomposition from: ESMs, FAIR GSAT ensemble members (global response), and METEOR internal variability.'
        })

    if 'var_int' in ds.variables:
        ds['var_int'].attrs.update({
            'description': 'variance from METEOR internal variability (noise) alone, calculated as ds.var(dim=\'noise_realisation\').mean(dim=[\'esm\', \'fair_realisation\'])'
        })
    if 'var_esm' in ds.variables:
        ds['var_esm'].attrs.update({
            'description': 'variance from ESM differences alone, calculated as dsds.mean(dim=\'noise_realisation\').var(dim=\'esm\').mean(dim=\'fair_realisation\')'
        })
    if 'var_global' in ds.variables:
        ds['var_global'].attrs.update({
            'description': 'variance from differences in global response (FAIR GSAT ensemble members) alone, calculated as ds.mean(dim=\'noise_realisation\').var(dim=\'fair_realisation\').mean(dim=\'esm\')'
        })
    if 'var_scenario' in ds.variables:
        ds['var_scenario'].attrs.update({
            'description': 'variance from scenario differences alone, calculated as ds.mean(dim=\'noise_realisation\').var(dim=[\'scenario\']).mean(dim=[\'esm\', \'fair_realisation\'])'
        })

def process_files(fair_pickle, file_list, suffix):
    with open(fair_pickle, "rb") as f:
        fair_ens = pickle.load(f)
        fair_members = fair_ens['ensemble_member'].unique()

    fair_members_attr = ", ".join(map(str, fair_members))

    for file in file_list:
        print(f"Updating attributes for {file}...")
        try:
            with xr.open_dataset(file) as ds:
                ds.load()
                update_attributes(ds, fair_members_attr)

                if suffix:
                    outfile = file.replace(".nc", f"_{suffix}.nc")
                else:
                    outfile = file

                ds.to_netcdf(outfile)
                print(f"Wrote {outfile}")

        except Exception as e:
            print(f"Failed for {file}: {e}")



def main():
    parser = argparse.ArgumentParser(description='Update NetCDF file attributes.')
    parser.add_argument(
        "fair_pickle",
        help="Pickle file containing FAIR ensemble member IDs"
    )
    parser.add_argument(
        "files",
        nargs="+",
        help="List of NetCDF files to process"
    )
    parser.add_argument(
        "--suffix",
        default="",
        help="Suffix to append before .nc when writing output files"
    )
    args = parser.parse_args()
    process_files(args.fair_pickle, args.files, args.suffix)


if __name__ == "__main__":
    main()

