import netCDF4
import glob
import datetime

# update FASTMIP output attributes

output_dir ='../data/FASTMIP_phase2/METEOR_emulations/processed/'

def update_attributes(ds):
    # global attributes:
    ds.attrs.update({
        'meteor_version': 'tag v1.6.0-10-g95e4345',
        'reference': 'https://doi.org/10.5194/egusphere-2026-2029 [preprint]',
        'ensemble_info': 'Full ensemble is 200 members per ESM per scenario (20 randomly chosen FAIR GSAT ensemble members x 10 METEOR noise/internal variability realisations). FAIR realisations are shared across ESMs and scenarios, noise realisations are independenly generated by METEOR for each ensemble member.',
        'authors': 'Maura Dewey (maura.dewey@cicero.oslo.no)',
        'date': datetime.datetime.now(datetime.UTC).isoformat()
        })

    # variable specific attributes:
    if 'tas' in ds.variables:
        ds['tas'].attrs.update({
            'description': 'Temperature emulation for FASTMIP phase 2',
            'units': 'K',
            'long_name': 'Near-surface air temperature anomaly',
            'standard_name': 'air_temperature',
            'reference_period': 'piControl'
        })

    if 'pr' in ds.variables:
        ds['pr'].attrs.update({
            'description': 'Precipitation emulation for FASTMIP phase 2',
            'units': 'kg m-2 s-1',
            'long_name': 'Near-surface precipitation rate anomaly',
            'standard_name': 'precipitation_flux',
            'reference_period': 'piControl'
        })

    if 'var_scenario' in ds.variables:
        ds.attrs.update({
            'description': 'variance decomposition from: ESMs, FAIR GSAT ensemble members (global response), scenarios, and METEOR internal variability.'
        })
    
    if 'var_global' in ds.variables and 'var_scenario' not in ds.variables:
        ds.attrs.update({
            'description': 'variance decomposition from: ESMs, FAIR GSAT ensemble members (global response), and METEOR internal variability.'
        })


# loop through all files:
for file in glob.glob(f"{output_dir}*H_meteor_regional_uncertainty.nc"):
    print(f"Updating attributes for {file}...")
    with netCDF4.Dataset(file, 'r+') as ds:
        update_attributes(ds)


